### ISSUE TITLE
Crashing on "Minecraft" Screen when starting

### ISSUE THREAD

**Issue by aotgamerz** [Dungeons-Guide/Skyblock-Dungeons-Guide#121]
Just crashes on Minecraft Screen. 
Check logs for more info

## **To Reproduce**
1. start Minecraft with mod

How to attach files??

**Comment by aotgamerz** [comment]
[2023-01-06-2.log.gz](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/10356669/2023-01-06-2.log.gz)
[crash-2023-01-06_01.18.04-client.txt](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/10356670/crash-2023-01-06_01.18.04-client.txt)

Logs here

**Comment by cyoung06** [comment]
Invalid lwjgl version, unsupported
