### ISSUE TITLE
DG conflicts with other mods causing OpenGL error: stack underflow

### ISSUE THREAD

**Issue by GraczBezNicku** [Dungeons-Guide/Skyblock-Dungeons-Guide#15]
The title says it all, but some details must be said.

It only occurs when you're in a dungeon.

_I decided to test if this error occurs when only DG is installed and I stumbled upon this problem once._

I'm playing on these mods installed using SkyblockClient installer:
- Skytils
- Danker's Skyblock Mod
- Custom Main Menu
- **Dungeons Guide 3.1.0**
- HUDCaching-1.8-REL
- Insomia
- itlt
- NotEnoughUpdates
- Optifine
- Patcher 1.5.1
- Popup Events
- Scrollable tooltips
- SkyblockAddons
- smooth-scrolling-everywhere
- TNT Time 1.0

The error only triggers when either:
1. A new pathfinding line is generated
2. A secret is picked up / opened / killed (bats)

_(sometimes though it occurs with no reason, but it's more likely it's just a secret getting picked up by someone else)_

Depending on how many times you get this error, some things may happen.
1. Flashing Background when in Inventory / Pause menu
2. Making the background completly non-transparent.
3. Flashing Items in inventory
4. Just crashing randomly

Just wanted to put it here since it's really annoying to restart your game after every dungeon run.

**Comment by wsquarepa** [comment]
Getting this issue as well still

**Comment by yodaluca23** [comment]
I don't know if this is related or not but sometimes it will glitch and keep pathfinding me to the same secret I already did and other times it just deletes itself and nothing works at all. I have to relaunch for it to work again...

This is my mod folder:

![image](https://user-images.githubusercontent.com/67206487/158084523-0fa1aeef-6ae4-40f0-bd2d-3424a2d80307.png)
