### ISSUE TITLE
DG for some reason doesn't work

### ISSUE THREAD

**Issue by MatDragon36055** [Dungeons-Guide/Skyblock-Dungeons-Guide#25]
For some reason upon launching the client when I use the mod it shows a screen full of text that looks like this: (in the link)
![obraz](https://user-images.githubusercontent.com/87947691/126910396-0f0d7808-fd65-4ebb-95ba-b83e2bb595e1.png)
I don't know what causes this but after that I can't even join Hypixel because it says that the session is invaild. Thank you for your response in advance.

**Comment by koxx12-dev** [comment]
2. If the first line of the error message says "InvalidCredentialsException" here are the steps to fix the problem.
- Close Minecraft
- Go to Minecraft Launcher
- Click your username, where it is displayed on the top left
- Click logout
- Click login
- Re-launch Minecraft Again 
If this keeps happening make sure you aren't using any third-party client other than skyclient. Also, try removing the dungeon guide mod from your mods folder and checking if you can join hypixel. If none of these steps work go to [#dg-support](https://discord.gg/sdg).

**Comment by cyoung06** [comment]
Closing
