### ISSUE TITLE
A lot of NullPonters

### ISSUE THREAD

**Issue by koxx12-dev** [Dungeons-Guide/Skyblock-Dungeons-Guide#27]
log: https://hst.sh/oxuziyojag (not the whole log but the issue)

this amount of NullPoinerExpeptions freezes my game and kills most of the runs cuz i get disconnected

if there is more info needed ping me on discord or mention me here

**Comment by koxx12-dev** [comment]
also here is my mod list
![image](https://user-images.githubusercontent.com/80456351/129607475-c0444951-5ca7-4ff2-a3b2-05ef3069f1f0.png)

**Comment by Feel65** [comment]
delete sba

**Comment by cyoung06** [comment]
at kr.syeyoung.dungeonsguide.dungeon.actions.ActionMove.onTick(ActionMove.java:86)

**Comment by cyoung06** [comment]
Should be fixed in new release
