### ISSUE TITLE
warping to floor 7 boss room makes game unplayable 

### ISSUE THREAD

**Issue by kaanyalova** [Dungeons-Guide/Skyblock-Dungeons-Guide#30]
warping to floor 7 boss room makes game unplayable until I reconnect 
issue still seems to happen with only optifine and dungeons guide 

here's a video of whats happening 

https://user-images.githubusercontent.com/76952012/131229604-4ead28f7-f680-471e-9e5d-13bf00590033.mp4

mod list 
![Ekran görüntüsü 2021-08-28 22-59-12](https://user-images.githubusercontent.com/76952012/131229631-171bfb26-03c6-415f-b004-574ce5dbd803.png)
issue still seems to happen after disabling every mod except optifine and dungeons guide 

[fml-client-latest.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/7071399/fml-client-latest.log)
log is mostly spammed by dungeons guide

**Comment by Feel65** [comment]
You’re…. Not using NEU

**Comment by kaanyalova** [comment]
do I need to use NEU?

**Comment by kaanyalova** [comment]
updated my mods ,no longer happens

**Comment by Feel65** [comment]
oh I wonder why
