### ISSUE TITLE
Dungeons Guide has ran into an error while loading itself.

### ISSUE THREAD

**Issue by LackingCats** [Dungeons-Guide/Skyblock-Dungeons-Guide#35]
![image](https://user-images.githubusercontent.com/92772508/142573350-4aba1502-faf8-4852-8ad7-a0b01bef1deb.png)
This is the first time this has happened (ever). Could you please explain to me what is going on and if you could (possibly) fix this?

**Comment by Anistorica** [comment]
did u solve it?

**Comment by Anistorica** [comment]
![(M29TJQVDW0)Z KPY2WTTQC](https://user-images.githubusercontent.com/91829926/142725796-55cbac67-ffae-4868-981e-1805d023254b.png)

**Comment by Anistorica** [comment]
i did the same situation

**Comment by LackingCats** [comment]
Mine seemed to be a one-time thing as I have just retried opening Minecraft with dungeons-guide and it has worked. Mine seems to be different from yours though, mine sent an ERROR: 403, and your connection is timing out. I'm sorry I can't help you, since I have no experience with this. Maybe wait for cyoung06 to respond ;-;

**Comment by Anistorica** [comment]
oh

**Comment by Anistorica** [comment]
[latest.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/7574523/latest.log)

**Comment by Anistorica** [comment]
its my logs hope someone could help me

**Comment by cyoung06** [comment]
Restart Minecraft.
