### ISSUE TITLE
Dungeons Guide has ran into an error while loading itself.help plz

### ISSUE THREAD

**Issue by Anistorica** [Dungeons-Guide/Skyblock-Dungeons-Guide#36]
![9EEX(0U H HD1@%$J_AQX H](https://user-images.githubusercontent.com/91829926/142726684-95880d08-2b82-4a44-9048-ed5902ea5bca.jpg
[latest.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/7574549/latest.log)
)

**Comment by Anistorica** [comment]
ive sent the logs

**Comment by cyoung06** [comment]
Restart Minecraft
