### ISSUE TITLE
DungeonsGuide ran into error while loading itself

### ISSUE THREAD

**Issue by IntoxicatedSoftware745** [Dungeons-Guide/Skyblock-Dungeons-Guide#38]
I have been having issues with this for a while now, I just have no idea how nor why it's broken, I can play without DG but it's not the same, I was just hoping someone could help me solve this issue, if needs be I can send the logs file, and if it helps I am using multi mc with forge on this instance
![image](https://user-images.githubusercontent.com/71582590/145874887-da699569-56c0-4c26-b85a-7799ed053db9.png)

**Comment by IntoxicatedSoftware745** [comment]
Another issue I noticed (I am not too sure if it's related or not) but when ever I load dungeons guide it doesn't allow me to connect to Hypixel, it will tell me that I have an "invalid session" and to restart my game, this is really strange and super annoying, please, if anyone knows of any fixes please let me know, I think this mod is sick and it's a real shame it ruins everything when I play with it.

**Comment by koxx12-dev** [comment]
it would be better if you asked on dg discord instead via github issues
https://discord.gg/h7j5m72zqW

**Comment by cyoung06** [comment]
Restart Minecraft
