### ISSUE TITLE
Do not click "AWW PENGUINS" in the menu

### ISSUE THREAD

**Issue by CitrusAcid** [Dungeons-Guide/Skyblock-Dungeons-Guide#402]
Seems to create the same issues as when people were holding banners in 1.8.9, except that the entire escape menu and settings disappear.  Restarting the game doesn't help. The attached image is a most tame example, as f2 doesn't take screenshots and I can't get an external software to work without the game pausing.
![image](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/142272105/024da495-e4e3-4225-add9-6a93ce01ec42)
![image](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/142272105/77faf87c-6afe-4af9-9a08-cb4bfd8cdd83)
![image](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/142272105/35bf793d-a1d6-46eb-b1bf-f35580c3ea64)

**Comment by CitrusAcid** [comment]
TO TURN OFF: Wait until skyblock marks you as afk and teleports you to the "move to reconnect room". From there, the menu will work as normal. I would guess not being in range of any other objects is the solution

**Comment by cyoung06** [comment]
Can not reproduce due to insufficient details.
