### ISSUE TITLE
Auth Error Occured Read timed out

### ISSUE THREAD

**Issue by Migouwel** [Dungeons-Guide/Skyblock-Dungeons-Guide#407]
So everytime i join in I receive this message in the bottom right corner of my screen, tried re-installing mod, nothing works, the message dosent dissapear, really annoying, **pls fix**.
![2023-09-04_11 47 12](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/144046751/3d1ba824-3359-482e-99c5-f2d1169da58c)
![2023-09-04_11 49 41](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/144046751/4945959c-3672-4250-8a57-6bfa94c13534)

**Comment by gobob** [comment]
yeah i have the same issue

**Comment by cyoung06** [comment]
dupe

**Comment by Migouwel** [comment]
Bruh its still not fixed
