### ISSUE TITLE
Game crashes when opened with other mods

### ISSUE THREAD

**Issue by MikaHD666** [Dungeons-Guide/Skyblock-Dungeons-Guide#45]
Title

Picture of my mod folder:
![Bild_2022-03-19_165041](https://user-images.githubusercontent.com/75185931/159128230-a6f83678-b219-4dd6-ba9c-ea8d59d3f808.png)

Picture of the error code on startup:
![Bild_2022-03-19_164715](https://user-images.githubusercontent.com/75185931/159128124-e64d48a6-3ada-4cf0-b880-a4bc193be9c8.png)

**Comment by BlueBeacon1244** [comment]
Same for me.

**Comment by Filakcz** [comment]
Yeah i get same. Yesterday it worked fine and today it isnt working. I changed nothing with my "setup".
My mods:
- Optifine
- Skyblock addons
- Dankers skyblock mod
- Bazaarnotifier
- Dungeon rooms
- NotEnoughUpdates
- Dungeons guide
- Skytils

**Comment by MikaHD666** [comment]
Okay, after trying to restart 11 times it suddenly works now.

**Comment by Filakcz** [comment]
I tried restarting PC twice and tried opening minecraft many times. Still doesnt work
