### ISSUE TITLE
UI does not scale with GUI scaling

### ISSUE THREAD

**Issue by Diliard** [Dungeons-Guide/Skyblock-Dungeons-Guide#47]
for People with an 4K screen its nearly impossible to read any UI because of it.

**Comment by Diliard** [comment]
update: just randomly came across how the UI scaling is done now, NAB then but there should probably be a notice or something to make it easier for people to find.

**Comment by cyoung06** [comment]
Working as intended, and yes I think the same, I should revamp the UX on dg 3.0.0.

**Comment by Diliard** [comment]
Thank you for the response!

If any Alpha/Beta commits appear in the near future about the UI I'll gladly try to help out by making PR's for it 👍
