### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION Crash on joining a party finder party

### ISSUE THREAD

**Issue by cursedgerbil** [Dungeons-Guide/Skyblock-Dungeons-Guide#48]
When joining a party through Party Finder, my game will often (around 60% of the time) immediately crash with an EXCEPTION_ACCESS_VIOLATION. This is usually just an error with accessing protected memory, but I combed through the error log and the issue seems to be related to Dungeons Guide. I would appreciate if you could investigate this. I've attached the related Java error log.

The console shows the following before the game crashes:

```
[16:38:54] [Client thread/INFO] [kr.syeyoung.dungeonsguide.chat.ChatProcessor]: [CHAT] §dDungeon Finder §r§f> §r§bGerbiil §r§ejoined the dungeon group! (§r§bTank Level 26§r§e)§r
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001cc253a0190, pid=20836, tid=0x0000000000004a88
#
# JRE version: Java(TM) SE Runtime Environment (8.0_311-b11) (build 1.8.0_311-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.311-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x000001cc253a0190
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\Minecraft\mmc-stable-win32\MultiMC\instances\1.8.9 (Skyblock)\.minecraft\hs_err_pid20836.log \\This log is attached below
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

[hs_err_pid20836.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/8399208/hs_err_pid20836.log)
Thank you.
Edit: fixed formatting, my bad!

**Comment by cyoung06** [comment]
Try 
1. Toggle off /dg -> Discord -> Disable Native Library
2. Restart
"OR"
1. Add "-Ddg.safe=true" jvm flag then start

**Comment by cursedgerbil** [comment]
Disabling the Discord Native Library fixed the issue, thanks!
