### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by kaanyalova** [Dungeons-Guide/Skyblock-Dungeons-Guide#49]
Mod crashes when trying to launch, without any other mods 

Log Files:
[hs_err_pid9107.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/8404346/hs_err_pid9107.log)
[fml-client-latest.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/8404357/fml-client-latest.log)

**Comment by cyoung06** [comment]
Try relaunching with `-Ddg.safe=true` jvm flag on

**Comment by kaanyalova** [comment]
Closing , because I don't play skyblock anymore
