### ISSUE TITLE
Screen goes blank on party finder settings

### ISSUE THREAD

**Issue by DefinitivVair0** [Dungeons-Guide/Skyblock-Dungeons-Guide#501]
When opening the party finder and clicking on settings, the screen goes blank except for a small square.

![image](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/148939542/f6647732-98f6-4b29-8929-7bfce158cdec)
![image](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/148939542/da0b116a-644f-49d4-8885-cdadcd94d079)

**Comment by cyoung06** [comment]
Could you please attach logs?

**Comment by DefinitivVair0** [comment]
> Could you please attach logs?

I hope this is what you're looking for.
[latest.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/14206681/latest.log)

**Comment by cyoung06** [comment]
Fix will be in next release
