### ISSUE TITLE
Dungeons Guide not working with In Game Account Switcher

### ISSUE THREAD

**Issue by QWERTZexe** [Dungeons-Guide/Skyblock-Dungeons-Guide#502]
**Describe the bug**

**To Reproduce**
1. Start forge with dungeonsguide and in game account switcher
2. Switch your account
3. Wait 10 seconds

**Expected behavior**
I can still join any server with the account i switched to. but i expect dungeonsguide to either work or add an option to hide this 
![SCREENSHOT 1](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/assets/109920359/35994172-026a-4d1b-846e-6858e0cd90e4)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: nt
 - Version 11
 - Browser: QWERTZ browser

**Additional context**
If you do not want to add support for in game account switcher, at least add an option to hide the popup

**Comment by cyoung06** [comment]
Click that pop-up to load dg again and hide it

**Comment by QWERTZexe** [comment]
> Click that pop-up to load dg again and hide it

I tried but it didnt work, this error always pops up when i click reload:
https://i.imgur.com/p6PhbSS.mp4

**Comment by cyoung06** [comment]
Click jar to load jar... 
Please read stuff on screen

**Comment by QWERTZexe** [comment]
> Click jar to load jar... 
> Please read stuff on screen

Where? Can you give me a timestamp of my video?

**Comment by cyoung06** [comment]
Click the literal button named jar on your screen

**Comment by QWERTZexe** [comment]
> Click the literal button named jar on your screen

I did and once I click load I see the mojang logo for 5 secs then get a massive error log

**Comment by cyoung06** [comment]
Keep doing it until it works
