### ISSUE TITLE
Screen Flash

### ISSUE THREAD

**Issue by DanchikBruh** [Dungeons-Guide/Skyblock-Dungeons-Guide#51]
Screen Constantly flashes and GUI View changes completely.
This is a problem involving only dungeonsguide as even if it is put up on forge by itself, without other mods it will still corrupt the output image.
(It only flashes when joining skyblock)
![image](https://user-images.githubusercontent.com/103369196/162620470-42a4da2f-9db0-4694-ad94-3da547495c1d.png)
This happens when you press ESC, otherwise it constantly turns the screen white.

**Comment by cyoung06** [comment]
Issue has been fixed

**Comment by DanchikBruh** [comment]
ty :) my friend happy now
