### ISSUE TITLE
Authenticator

### ISSUE THREAD

**Issue by LeonDaviid** [Dungeons-Guide/Skyblock-Dungeons-Guide#55]
Why did you add this Authenticator?
There is no reason to a send userdata to a domain or touch the session token.
Getting JustEnoughDungeons vibes :P

How to remove this "feature"? Would it work to remove the preInit function from Main.java?

**Comment by cyoung06** [comment]
You need a bit of history in dg to understand why the Authenticator exists

It exists as a purpose to verify your identity as a Minecraft user, and get you the "dungeons guide access token"

This thing is used to communicate with dungeons guide backend handling mostly cosmetic stuff, internal party communication, auction data fetching, auto-update for supporters (if ur pro-java-developer you would know it allows dynamic class loading if entrypoint does not exist), and many other stuff including Mayor Score collection and stuff.

on the history of dungeons guide:
Dungeons Guide was initially a paid mod, and I spent a lot of time making it hard for people to crack.
The dynamic loading mechanism was result of that, and I had to add the authenticator


Anyways, also on that JustEnoughDungeons vibe: 
if you know coding, you know it isn't just enough dungeons
session token is only sent to mojang's server (the thing used to authenticate you through hypixel or any other Minecraft servers0
that means, I don't get any of your session tokens

You do not want to remove this feature. It will not work to just remove preinit function from Main.java

Anyways a lot of things on dungeons guide depend on websocket which requires the dungeons guide access token, so you would have to spend a lot of time removing all that.
In the end, you will leave your custom dungeons guide unable to connect with other dungeons guide and provide useful features in the future.
