### ISSUE TITLE
Game crashes when loading DungeonsGuide

### ISSUE THREAD

**Issue by vsjoqvist** [Dungeons-Guide/Skyblock-Dungeons-Guide#58]
When forge starts to load the mod the window freezes and then crashes with the exit code 6.

I run linux in case it matters but i don't see how to could be the problem

---

Minecraft log
[latest.log](https://github.com/Dungeons-Guide/Skyblock-Dungeons-Guide/files/9439531/latest.log)

**Comment by cyoung06** [comment]
Mod support is provided at 
https://discord.gg/dg

Please keep github issues for real issues.
