### ISSUE TITLE
Dg has ran into an error while running itself

### ISSUE THREAD

**Issue by lexvato** [Dungeons-Guide/Skyblock-Dungeons-Guide#67]
When i was using skyclient i opened it and DG ran into an error

![Screenshot 2022-10-20 183641](https://user-images.githubusercontent.com/70668844/197084804-9b5ae206-8461-410b-bb26-dc8150aefda6.png)
here an image

**Comment by kingstefan26** [comment]
fixed in #70 go over to discord and download beta there
