### ISSUE TITLE
dungeons guide not working on skyclient

### ISSUE THREAD

**Issue by conorrrrrrrr** [Dungeons-Guide/Skyblock-Dungeons-Guide#82]
I was trying to play skyblock today on skyclient, because its easier to get the best mods, and this poped up.
![image](https://user-images.githubusercontent.com/120219895/206790069-768f42e1-93f1-49c4-b855-50f919ee24cf.png)

I don't know if the image worked, but basically it said that dungeons guide has run into an error loading itself. please contact support.

So yeah, how do i fix it?

**Comment by SethKirigaya** [comment]
that happened to me too

**Comment by cyoung06** [comment]
Mojang or Minecraft issue
